=== SKA-ScienceDataProcessor/integration-prototype/sip/execution_control/configuration_db/redis/schema/scheduling_block_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Scheduling Block Instance",
    "description": "Schema for an SKA Scheduling Block Instance",
    "type": "object",

    "properties": {
        "sched_block_id": {
            "description": "[date]-[project]-[type][id] for the scheduling block id",
            "type": "string"
        },
        "name": {
            "description": "Optional name string",
            "type": "string"
        },
        "sched_block_instance_id": {
            "description": "[date]-[project]-[type][id] for the scheduling block instance id",
            "type": "string"
        },
        "type": {
            "description": "Type of scheduling block",
            "type": "string"
        },
        "date": {
            "description": "YYmmdd for the date",
            "type": "string"
        },
        "sub_array_id": {
            "description": "[date]-[project]-[type][id] for the sub array id",
            "type": "string"
        },
        "status": {
            "description": "Status of the scheduling block instance",
            "type": "string"
        },
        "version": {
            "description": "Version of the scheduling block instance",
            "type": "string"
        },
        "project": {
            "description": "Project of the scheduling block instance",
            "type": "string"
        },
        "processing_blocks" : {"$ref": "#/definitions/blocks"}
    },

    "required": ["sched_block_id", "sched_block_instance_id", "sub_array_id", "processing_blocks"],

    "definitions": {
        "blocks": {
            "description": "Array of processing blocks associated with this scheduling block",
            "type": "array",
            "items": {
                "description": "Processing block specification - description of required processing",
                "type": "object",
                "properties": {
                    "id": {
                        "description": "[date]-[project]-[type][id] for the processing block",
                        "type": "string"
                    },
                    "type": {
                        "description": "Type of the processing block",
                        "type": "string"
                    },
                    "priority": {
                        "description": "The Priority of the processing block",
                        "type": "number"
                    },
                    "status": {
                        "description": "Status of the processing block",
                        "type": "string"
                    },
                    "resources_requirement" : {"$ref": "#/definitions/resource_requirement"},
                    "assigned_resources" : {"$ref": "#/definitions/assigned_resources"},
                    "workflow" : {"$ref": "#/definitions/workflow"}
                },
                "required": ["id", "resources_requirement"]
            }
        },

        "resource_requirement": {
            "description": "Resource required for the processing block",
            "type": "object",
            "properties": {
                "storage_type": {
                    "description": "Hot or cold buffer storage type",
                    "type": "string"
                }
            }
        },

        "assigned_resources": {
            "description": "Resource assigned for the processing block",
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status of the resource assigned",
                    "type": "string"
                }
            }
        },

        "workflow": {
            "description": "Workflow stages",
            "type": "object",
            "properties": {
                "status": {
                "description": "Status of the workflow stage",
                "type": "string"
                }
            }
        }
    }
}

=== SKA-ScienceDataProcessor/integration-prototype/sip/execution_control/configuration_db/redis/utils/scheduling_block_data.json
{
  "sched_block_id": "20180201-test-sb000",
  "name": "Optional name string",
  "sched_block_instance_id": "20180201-test-sbi000",
  "type": "Scheduling Block Instance",
  "date": "20180201",
  "sub_array_id": "subarray000",
  "version": "0.2",
  "project": "sip",
  "processing_blocks": [
    {
      "id": "sip-vis000",
      "type": "vis_ingest",
      "priority": 1,
      "resources_requirement": {
      "storage_type": "hot"
      },
      "workflow": {
      }
    },
    {
      "id": "sip-vis001",
      "type": "vis_ingest",
      "priority": 2,
      "resources_requirement": {
      "storage_type": "hot"
      },
      "workflow": {
      }
    }
  ]
}

=== SKA-ScienceDataProcessor/integration-prototype/sip/execution_control/processing_controller_scheduler/asyncio_celery/schema/scheduling_block_instance_data.json
{
  "sched_block_id": "180201-sch-bl0",
  "name": "Optional name string",
  "sched_block_instance_id": "180201-sched-blinst0",
  "type": "Schedling Block Instance",
  "date": "180201",
  "sub_array_id": "180201-subarray-ant0",
  "version": "0.2",
  "project": "sip",
  "processing_blocks": [
    {
      "id": "180201-sip-vis0",
      "type": "vis_ingest",
      "priority": 1,
      "resources_requirement": {
      "storage_type": "hot"
      },
      "workflow": {
        "stages" : [
          {
            "processing_stage": {
              "start_time": "",
              "end_time": "",
              "processing_component":{
              },
              "execution_engine": {
                "framework": ""
              }
            },
            "service_stage": {
              "buffer":"",
              "preservation":"",
              "model_database":"",
              "data_queue":"",
              "delivery":""

            },
            "dependency" : {
              "sky_model_tag_id": "optional",
              "telescope_model_tag_id" :"optional",
              "data_queue_id": "optional",
              "buffer_object_id": "optional"
            }
          }
        ]
      }
    },
    {
      "id": "180201-sip-vis1",
      "type": "vis_ingest",
      "priority": 2,
      "resources_requirement": {
      "storage_type": "hot"
      },
      "workflow": {
        "stages" : [
          {
            "processing_stage": {
              "start_time": "",
              "end_time": "",
              "processing_component":{
              },
              "execution_engine": {
                "framework": ""
              }
            },
            "service_stage": {
              "preservation":"",
              "model_database":"",
              "data_queue":"",
              "delivery":""

            },
            "dependency" : {
              "sky_model_tag_id": "optional",
              "telescope_model_tag_id" :"optional",
              "data_queue_id": "optional",
              "buffer_object_id": "optional"
            }
          }
        ]
      }
    }
  ]
}
