=== SKA-ScienceDataProcessor/integration-prototype/emulators/csp_vis_sender_01/etc/configuration_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "SIP CSP Visibility Sender Configuration",
    "description": "Schema for the SIP CSP Visibility Sender .",
    "version": "1",
    "type": "object",
    "required": ["spead_flavour", "observation", "sender_node"],
    "properties": {
        "spead_flavour": {
            "description": "SPEAD flavour configuration",
            "type": "object",
            "required": [],
            "properties": {
                "version": { "type": "integer" },
                "item_pointer_bits": { "type": "integer" },
                "heap_address_bits": { "type": "integer" },
                "bug_compat_mask": { "type": "integer" }
            }
        },
        "observation": {
            "description": "Observation parameters which effect dimensions of the SPEAD packet",
            "type": "object",
            "required": [],
            "properties": {
                "num_stations": { "type": "integer" },
                "num_channels": { "type": "integer" },
                "num_times": { "type": "integer" }
            }
        },
        "simulation": {
            "description": "Placeholder field for simulation settings",
            "type": "object",
            "required": [],
            "properties": {}
        },
        "sender_node": {
            "description": "",
            "type": "object",
            "required": ["start_channel", "streams"],
            "properties": {
                "start_channel": { "type": "integer" },
                "streams": {
                    "type": "array",
                    "items": {
                        "description": "SPEAD stream specification",
                        "type": "object",
                        "required": ["port", "host"],
                        "properties": {
                            "port": {"type": "integer"},
                            "host": {"type": "string"},
                            "threads": {"type": "integer"}
                        }

                    }
                }
            }
            
        }
    }
}

=== SKA-ScienceDataProcessor/integration-prototype/emulators/csp_visibility_sender/etc/config.json
{
  "spead_flavour": {
    "version": 4,
    "item_pointer_bits": 64,
    "heap_address_bits": 40,
    "bug_compat_mask": 0
  },

  "observation":
  {
    "num_stations": 512,
    "num_channels": 4,
    "num_times": 9
  },

  "simulation": {
    "TBD": "xxx"
  },

  "sender_node": {
    "start_channel": 0,
    "streams": [
      {
        "port": 8001,
        "host": "127.0.0.1",
        "threads": 1,
        "rate": 0
      }
    ]
  }
}
